### PR TITLE
Minor fixes

### PR DESCRIPTION
**Pull request by josharian**
Please review carefully--I am not set up to actually run these changes, and there are no tests.

(Relatedly, it'd be nicer not to check in your go.mod pion replace directives.)

### CODE REVIEW

**Comment by cedricfung** [comment]
I just checked the doc https://golang.org/pkg/time/#Timer.Reset

```
Reset should be invoked only on stopped or expired timers with drained channels.

if !t.Stop() {
	<-t.C
}
t.Reset(d)
```

Does it mean that we can't use Reset() like this?

**Comment by josharian** [comment]
Huh. Good question. @ianlancetaylor, what is the preferred way to create a timer and then repeatedly kick it to some point further in the future, in performance sensitive code?

**Comment by josharian** [comment]
Sorry for the noise, Ian. I was confused about the interaction with the timer.Stop proposal.

**Comment by josharian** [comment]
@cedricfung please take another look. The new code is still significantly more performant: ~93ns/op instead of ~270ns/op, and no allocs instead of 208B/3allocs.

**Comment by cedricfung** [comment]
But I feel that `<-timer.C` will block the loop until timer expires?

**Comment by cedricfung** [comment]
sorry, my misunderstanding.

**Pull request merged**
